<?php

namespace App\Filament\Resources;

use App\Filament\Resources\BirthCertificateFormResource\Pages;
use App\Filament\Resources\BirthCertificateFormResource\RelationManagers;
use App\Models\BirthCertificateForm;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class BirthCertificateFormResource extends Resource
{
    protected static ?string $model = BirthCertificateForm::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('n_first_name')
                    ->required()
                    ->maxLength(100),
                Forms\Components\TextInput::make('n_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_surname')
                    ->required()
                    ->maxLength(100),
                Forms\Components\TextInput::make('e_first_name')
                    ->required()
                    ->maxLength(100),
                Forms\Components\TextInput::make('e_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_surname')
                    ->required()
                    ->maxLength(100),
                Forms\Components\DatePicker::make('birth_date')
                    ->required(),
                Forms\Components\TextInput::make('gender')
                    ->required(),
                Forms\Components\TextInput::make('birth_type')
                    ->required(),
                Forms\Components\Toggle::make('is_weight_taken'),
                Forms\Components\TextInput::make('birth_weight')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('birth_attendant_type')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('birth_place')
                    ->required(),
                Forms\Components\TextInput::make('birth_province')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('birth_municipality')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('birth_ward')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('n_birth_country')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_birth_state')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_birth_local_address')
                    ->maxLength(255)
                    ->default(null),
                Forms\Components\TextInput::make('e_birth_country')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_birth_state')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_birth_local_address')
                    ->maxLength(255)
                    ->default(null),
                Forms\Components\Textarea::make('disable_type')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('n_grandfather_first_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_grandfather_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_grandfather_last_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_grandfather_first_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_grandfather_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_grandfather_last_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_father_first_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_father_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_father_last_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_father_first_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_father_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_father_last_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_mother_first_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_mother_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_mother_last_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_mother_first_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_mother_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_mother_last_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('father_province')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('father_municipality')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('father_ward')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('father_street')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('father_village')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('father_house_no')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('father_citizenship_no')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\DatePicker::make('father_dob'),
                Forms\Components\TextInput::make('father_education')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\Textarea::make('father_occupation')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('father_religion')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('father_cast')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('mother_province')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('mother_municipality')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('mother_ward')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mother_street')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('mother_village')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('mother_house_no')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mother_citizenship_no')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\DatePicker::make('mother_dob'),
                Forms\Components\TextInput::make('mother_education')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\Textarea::make('mother_occupation')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('mother_religion')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('mother_cast')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('father_passport_no')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('father_country')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('mother_passport_no')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('mother_country')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('marriage_registration_no')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\DatePicker::make('marriage_date'),
                Forms\Components\TextInput::make('n_informer_first_name')
                    ->required()
                    ->maxLength(100),
                Forms\Components\TextInput::make('n_informer_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_informer_last_name')
                    ->required()
                    ->maxLength(100),
                Forms\Components\TextInput::make('e_informer_first_name')
                    ->required()
                    ->maxLength(100),
                Forms\Components\TextInput::make('e_informer_middle_name')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('e_informer_last_name')
                    ->required()
                    ->maxLength(100),
                Forms\Components\TextInput::make('informer_relation_with_child')
                    ->required()
                    ->maxLength(50),
                Forms\Components\TextInput::make('citizenship_number')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('e_passport_number')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('n_passport_number')
                    ->maxLength(50)
                    ->default(null),
                Forms\Components\TextInput::make('e_issued_country')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('n_issued_country')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\DatePicker::make('form_filled_date')
                    ->required(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('n_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_surname')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_surname')
                    ->searchable(),
                Tables\Columns\TextColumn::make('birth_date')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gender'),
                Tables\Columns\TextColumn::make('birth_type'),
                Tables\Columns\IconColumn::make('is_weight_taken')
                    ->boolean(),
                Tables\Columns\TextColumn::make('birth_weight')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('birth_attendant_type')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('birth_place'),
                Tables\Columns\TextColumn::make('birth_province')
                    ->searchable(),
                Tables\Columns\TextColumn::make('birth_municipality')
                    ->searchable(),
                Tables\Columns\TextColumn::make('birth_ward')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('n_birth_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_birth_state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_birth_local_address')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_birth_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_birth_state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_birth_local_address')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_grandfather_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_grandfather_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_grandfather_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_grandfather_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_grandfather_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_grandfather_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_father_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_father_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_father_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_father_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_father_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_father_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_mother_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_mother_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_mother_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_mother_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_mother_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_mother_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_province')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_municipality')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_ward')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('father_street')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_village')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_house_no')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('father_citizenship_no')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_dob')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('father_education')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_religion')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_cast')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_province')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_municipality')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_ward')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mother_street')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_village')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_house_no')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mother_citizenship_no')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_dob')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mother_education')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_religion')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_cast')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_passport_no')
                    ->searchable(),
                Tables\Columns\TextColumn::make('father_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_passport_no')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mother_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('marriage_registration_no')
                    ->searchable(),
                Tables\Columns\TextColumn::make('marriage_date')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('n_informer_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_informer_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_informer_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_informer_first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_informer_middle_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_informer_last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('informer_relation_with_child')
                    ->searchable(),
                Tables\Columns\TextColumn::make('citizenship_number')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_passport_number')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_passport_number')
                    ->searchable(),
                Tables\Columns\TextColumn::make('e_issued_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('n_issued_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('form_filled_date')
                    ->date()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListBirthCertificateForms::route('/'),
            'create' => Pages\CreateBirthCertificateForm::route('/create'),
            'view' => Pages\ViewBirthCertificateForm::route('/{record}'),
            'edit' => Pages\EditBirthCertificateForm::route('/{record}/edit'),
        ];
    }
}
